### ISSUE TITLE
Add open-source license for this project

### ISSUE THREAD

**Issue by yechs** [endiliey/wait-file#2]
Hi, I discovered that this package is a direct dependency of [@docusaurus/core](https://www.npmjs.com/package/@docusaurus/core), which is licensed under the MIT license.

However, this repo itself does not contain a license, which means, strictly speaking, these codes cannot be used within docusaurus (and any other projects depending on docusaurus).

Could you fix this by adding an open-source license to this repo? Thanks!

**Comment by endiliey** [comment]
My bad, I will add it soon

**Comment by yechs** [comment]
Sure, thank you!
